# /.github/workflows/dockerHub.yml

name: DockerHub
on: push
jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: All Files
        run: ls

      - name: Unit-tests
        run: cd carSharing && chmod +x gradlew && ./gradlew test

  build-to-docker:
    needs: [tests]
    name: Push to docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Working Directory is
        run: pwd
      - name: All Files
        run: ls
      - name: Build with Gradle
        run: cd AuthService && chmod +x gradlew && ./gradlew build && cd ..
      - name: Build docker image
        working-directory: 'AuthService'
        run: docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/auth-service-workflow:test .
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/auth-service-workflow:test

  push-to-yandex:
    needs: [ tests ]
    name: Push to Yandex Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build with Gradle
        run: cd carSharing && chmod +x gradlew && ./gradlew build
      - name: Build docker image
        working-directory: 'carSharing'
        run: docker build -f Dockerfile -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/zakharov-car-sharing-service:test .
      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}
      - name: Push tag to YC Registry
        run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/zakharov-car-sharing-service:test

  deploy-service:
    needs: [ push-to-yandex ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy serverless container
        uses: yc-actions/yc-sls-container-deploy@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/zakharov-car-sharing-service:test
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
